global:
  name: Hyperledger Landscape
  short_name: Hyperledger
  repo: hyperledger-landscape/hl-landscape
  website: https://landscape.hyperledger.org
  short_domain: l.hyperledger.org
  company_url: https://hyperledger.org
  email: info@hyperledger.org
  self: https://www.crunchbase.com/organization/hyperledger-2
  slack_channel: T08PSQ7BQ/BNJ3M745N/SuoWYz5SmLz0D0T76ErdM8ba
  meta:
    title: Hyperledger Landscape
    fb_admin: alex.contini.94
    description: Filter and sort by GitHub stars, funding, commits, contributors, hq location, and tweets
    twitter: '@hyperledger'
    google_site_verification: 02nZnXMMckSXVC6dBaHQQgMbpymdaQr-2l8zRKLgsaY
    ms_validate: 3AF9FFA12CCC3C49C0ABA71CCA222665
  membership: Hyperledger Members
  flags:
    companies: Hyperledger Members
    hide_license_for_categories:
      - Hyperledger Certified Service Providers
twitter:
  search: landscape.hyperledger.org
  url: https://landscape.hyperledger.org
  text: Hyperledger Landscape
relation:
  label: Hyperledger Relation
  url: hyperledger
  values:
    - id: hosted
      label: Hyperledger Projects
      children:
        - id: graduated
          label: Graduated Hyperledger Projects
          prefix: Hyperledger
          tag: Graduated
          color: '#3570af'
          big_picture_order: 1
          big_picture_label: Graduated
          big_picture_color: rgb(24,54,114)
        - id: incubating
          label: Incubating Hyperledger Projects
          prefix: Hyperledger
          tag: Incubating
          color: '#00cbff'
          big_picture_order: 2
          big_picture_label: Incubating
          big_picture_color: rgb(83, 113, 189)
    - id: company
      label: Hyperledger Members
      tag: Company
      big_picture_order: 3
    - id: member
      label: Hyperledger Project Member Products/Projects
      tag: Hyperledger Member
    - id: false
      label: Non-Hyperledger Project Member Products/Projects
      url: 'no'
membership:
  Premier:
    name: Hyperledger
    label: Member
    funding: Premier
    is_large: true
  General:
    name: Hyperledger
    label: Member
    funding: General
  Associate:
    name: Hyperledger
    label: Member
    funding: Associate
  linux_foundation:
    name: LF
    label: Project
    funding: Linux Foundation
    crunchbase_and_children: https://www.crunchbase.com/organization/linux-foundation
  'false':
    funding: 'No'
home:
  header: >
    <h1>Hyperledger Landscape</h1> The Hyperledger landscape (<a target="_blank" href="images/landscape.png">png</a>, <a target="_blank"
    href="images/landscape.pdf">pdf</a>) is dynamically generated below. It is modeled after the <a href="http://landscape.cncf.io">CNCF landscape</a> and based
    on the same open source code.
  footer: |
    Crunchbase data is used under license from Crunchbase to CNCF.
ads:
  - url: https://events.linuxfoundation.org/hyperledger-global-forum/
    image: /images/HGF2021.jpeg
    title: Hyperledger Global Forum 2021
presets:
  - url: /format=card-mode&grouping=no&license=open-source&sort=first-commit
    label: Open source cards by age
  - url: /license=apache-license-2-0
    label: Apache-2.0 landscape
  - url: /format=card-mode&grouping=category
    label: Cards in categories
  - url: /format=card-mode&grouping=no&sort=stars
    label: Cards by stars
  - url: /format=card-mode&grouping=headquarters
    label: Group by location
  - url: /format=card-mode&grouping=no&sort=amount
    label: Cards by MCap/Funding
big_picture:
  main:
    tab_index: -1
    url: landscape
    name: Landscape
    title: Hyperledger Landscape
    fullscreen_header: See the interactive landscape at l.hyperledger.org
    elements:
      - type: HorizontalCategory
        category: Hyperledger Projects
        rows: 6
        width: 800
        height: 1200
        top: 0
        left: 0
        color: rgb(4,81,49)
        fit_width: true
      - type: HorizontalCategory
        category: Hyperledger Certified Service Providers
        rows: 3
        width: 525
        height: 160
        top: 0
        left: 0
        color: rgb(19,105,73)
        fit_width: true
      - type: HorizontalCategory
        category: Hyperledger Training Partner
        rows: 4
        width: 795
        height: 160
        top: 200
        left: 0
        color: rgb(126,115,14)
        fit_width: true
      - type: HorizontalCategory
        category: Hyperledger Members
        rows: 7
        width: 730
        height: 1200
        top: 500
        left: 400
        color: rgb(143,66,16)
        fit_width: true
      - type: LandscapeInfo
        width: 365
        height: 200
        top: 0
        left: 745
        children:
          - type: text
            text: |
              This landscape is intended as a map to explore the Hyperledger community, and also shows the member organizations of Hyperledger.
            top: 45
            left: 100
            right: 120
            font_size: 10
          - type: image
            image: qr.svg
            top: 40
            left: 5
            width: 90
            height: 90
            title: QR Code
          - type: title
            title: l.hyperledger.org
            top: 129
            left: 19
            font_size: 21
          - type: image
            image: left-logo.svg
            width: 110
            right: 5
            top: 45
            title: Landscape Logo
          - type: image
            image: right-logo.svg
            width: 109
            right: 5
            top: 85
            title: Hyperledger Logo
test:
  header: Hyperledger Landscape
  section: Hyperledger Members
  logo: international-business-machines-corporation-ibm.svg
prerender:
  csp: /card-mode?category=hyperledger-fabric-csp&grouping=category&embed=yes
  members: /card-mode?grouping=category&project=company&embed=yes&style=borderless
