name: Update members

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout landscape
        uses: actions/checkout@v2
        with:
          path: landscape
      - name: Checkout landscapeapp
        uses: actions/checkout@v2
        with:
          repository: cncf/landscapeapp
          path: landscapeapp

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Yarn install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
          dir: landscapeapp

      - name: cleanup yml files
        run: |
          cd landscapeapp
          PROJECT_PATH=../landscape yarn remove-quotes
          PROJECT_PATH=../landscape yarn prune

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          branch-suffix: timestamp
          path: ./landscape
          title: Update members
          labels: automated-build
          commit-message: Update members
